// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whwywpzaqlrypqqjsyrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indod3l3cHphcWxyeXBxcWpzeXJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MjQwMDksImV4cCI6MjA2MDUwMDAwOX0.xIPcvnfTSmHaLsJ-DhkORPi9ssBgMmLTJ1w7MPlFFgI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);